#include<iostream.h>
#include<conio.h>
void sc1()
{
cout<<endl<<"Scheme 1 Details"<<endl<<endl;
cout<<"Natural Crisis Vima Yojana"<<endl;
cout<<"The agriculture sector contributed 51.9 percent to India’s GDP in 1950. Since then it has been on a downside and it currently stands at 13.9 percent. However, a change from an agrarian-centric economy to an industry-centric economy is inevitable with the advent of industries. With industries growing at a faster pace than the rate at which trees are being planted, will there be a time when agriculture’s productivity dwindles to a null? If yes, is it already here?";
}
void sc2()
{
cout<<endl<<"Scheme 2 Details"<<endl<<endl;
cout<<"Pradhan Mantri Fasal Bima Yojana\n";
cout<<"Farming has become an unreliable sector. Farmers are always unsure of the yield they’ll reap, but strive to draw the maximum benefits out of their investments and effort. Often farmers might be at the receiving end, with natural calamities like droughts and floods affecting their yield adversely. To resolve the problem of unpredictable nature of farming and prevent farmer suicides in the country, the Government launched PM Mantri Fasal Bima Yojana in early 2016. It’s a crop insurance policy with relaxed premium rates on the principal sum insured for farmers. Implemented with a budget of Rs 17,600 crore, this scheme will provide financial support to farmers and cover for their losses. This initiative is expected to go on floors from the next Kharif season of farming, that is from June 2016.";
}
void sc3()
{
cout<<endl<<"Scheme 3 Details"<<endl<<endl;
cout<<" Paramparagat Krishi Vikas Yojana\n";
cout<<"The government has launched Paramparagat Krishi Vikas Yojana in order to address the critical importance of soil and water for improving agricultural production. The government would support and improve the organic farming practices prevalent in India. Following cluster approach mode of farming, at least 50 farmers would form a group having 50 acres of land to implement organic farming. The government aims to cover 10,000 clusters and five lakh hectares of arable land under organic farming within three years.";
}



